// w64_d8192.v

// Generated using ACDS version 23.3 104

`timescale 1 ps / 1 ps
module w64_d8192 (
		input  wire [63:0] data,      //      data.datain
		output wire [63:0] q,         //         q.dataout
		input  wire [12:0] wraddress, // wraddress.wraddress
		input  wire [12:0] rdaddress, // rdaddress.rdaddress
		input  wire        wren,      //      wren.wren
		input  wire        clock,     //     clock.clk
		input  wire        sclr       //      sclr.reset
	);

	w64_d8192_ram_2port_2041_tpys6ny ram_2port_0 (
		.data      (data),      //   input,  width = 64,      data.datain
		.q         (q),         //  output,  width = 64,         q.dataout
		.wraddress (wraddress), //   input,  width = 13, wraddress.wraddress
		.rdaddress (rdaddress), //   input,  width = 13, rdaddress.rdaddress
		.wren      (wren),      //   input,   width = 1,      wren.wren
		.clock     (clock),     //   input,   width = 1,     clock.clk
		.sclr      (sclr)       //   input,   width = 1,      sclr.reset
	);

endmodule
