// port_1_ram.v

// Generated using ACDS version 23.3 104

`timescale 1 ps / 1 ps
module port_1_ram (
		input  wire [13:0] data,    //    data.datain
		output wire [13:0] q,       //       q.dataout
		input  wire [11:0] address, // address.address
		input  wire        wren,    //    wren.wren
		input  wire        clock    //   clock.clk
	);

	port_1_ram_ram_1port_2011_puertoy ram_1port_0 (
		.data    (data),    //   input,  width = 14,    data.datain
		.q       (q),       //  output,  width = 14,       q.dataout
		.address (address), //   input,  width = 12, address.address
		.wren    (wren),    //   input,   width = 1,    wren.wren
		.clock   (clock)    //   input,   width = 1,   clock.clk
	);

endmodule
